### ISSUE TITLE
missing package ttf-dejavu causing python to not be installed

### ISSUE THREAD

**Issue by abhishekjain14** [mdhiggins/sma-mod#10]
When starting a Sonarr container with this as a docker mod:

sonarr         | E: Unable to locate package ttf-dejavu
sonarr         | [90-sma-config] Creating python virtual environment and installing requirements
sonarr         | /etc/s6-overlay/s6-rc.d/init-sma-config/run: line 89: python3: command not found
sonarr         | /etc/s6-overlay/s6-rc.d/init-sma-config/run: line 90: /usr/local/sma/venv/bin/python3: No such file or directory
sonarr         | /etc/s6-overlay/s6-rc.d/init-sma-config/run: line 91: /usr/local/sma/venv/bin/pip: No such file or directory
sonarr         | [90-sma-config] Installing additional deluge/qbittorrent requirements
sonarr         | /etc/s6-overlay/s6-rc.d/init-sma-config/run: line 95: /usr/local/sma/venv/bin/pip: No such file or directory
sonarr         | [90-sma-config] Set FFMPEG URL to https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
sonarr         | [90-sma-config] Downloading and installing FFMpeg from https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
sonarr         | tar (child): xz: Cannot exec: No such file or directory
sonarr         | tar (child): Error is not recoverable: exiting now
sonarr         | tar: Child returned status 2
sonarr         | tar: Error is not recoverable: exiting now
sonarr         | chown: cannot access '/usr/local/bin/ffmpeg': No such file or directory
sonarr         | chown: cannot access '/usr/local/bin/ffprobe': No such file or directory
sonarr         | chmod: cannot access '/usr/local/bin/ffmpeg': No such file or directory
sonarr         | chmod: cannot access '/usr/local/bin/ffprobe': No such file or directory
sonarr         | /etc/s6-overlay/s6-rc.d/init-sma-config/run: line 143: /usr/local/sma/venv/bin/python3: No such file or directory
sonarr         | s6-rc: warning: unable to start service init-sma-config: command exited 127

**Comment by mdhiggins** [comment]
Pushed an update, looks like that package was renamed
