### ISSUE TITLE
nzbget container not installing requests

### ISSUE THREAD

**Issue by abhishekjain14** [mdhiggins/sma-mod#11]
When the NZBget container is pulled, with a base image of alpine, the requests library isn't installed. It's easily fixed by going into the docker container and manually rerunning     

```
${SMA_PATH}/venv/bin/pip install -q --no-cache-dir \
        -r ${SMA_PATH}/setup/requirements.txt > /dev/null
```

but any thoughts on how to fix this?

**Comment by mdhiggins** [comment]
Any errors from the docker logs during the initial setup?

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sma-mod/tree/s6v2

Nevermind, the issue is that linuxserver has migrated their containers to s6v3 and sma-mod was updated to support this

Legacy containers will need to sue the s6v2 tag. NZBGet is a deprecated container so linuxserver hasn't updated it to s6v3
