### ISSUE TITLE
Docker mod

### ISSUE THREAD

**Issue by abhishekjain14** [mdhiggins/sma-mod#4]
I've been considering using this with nzbget instead of radarr/sonarr to simplify my workflow and have the conversions happen on a local disk instead of a NAS. I don't see any up to date containers out there, but came across this little tidbit: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

Any reason SMA couldn't work as a docker mod, allowing us the capability to add it into any container that could use it? If not, any interest in doing so, @mdhiggins? If not, I'd be willing to give it a try.

**Comment by mdhiggins** [comment]
0f461997c1ce1d214d76fb3a0df33a952ccaaf6d

Pushed an update that just sets ffmpeg/ffprobe generically instead of a specific path, if you want to override your ffmpeg/ffprobe binaries just put them somewhere in the path so that they are recognized by `which ffmpeg` and `which ffprobe`

That should help

**Comment by mdhiggins** [comment]
You'll need to mount ffmpeg/ffprobe somewhere within your system PATH
that will not only prevent the startup script from downloading it but also prevent the path issue

**Comment by mdhiggins** [comment]
Sadly no. For small changes to the main script SMA_UPDATE is enough but this needed more. Looks like that worked though the paths were left alone. Is that working for you?

**Comment by mdhiggins** [comment]
Forgot you were on s6v2, I haven't brought those changes to s6v2 so I just merged them over from master

Can you share your full docker config? The more logs you post the less sense the setup is making

**Comment by mdhiggins** [comment]
Share you docker config

**Comment by mdhiggins** [comment]
Alright so this is a bit confusing and I guess I'm not fully sure what your aim is here. I'm guessing just looking at this you're trying to set up intel based hardware acceleration? correct me if that's not the case

You're making a few fundamental mistakes here and also creating lots of work for yourself

- SMA_PATH only needs to be set if you're overriding it
- SMA_FFMPEG/FFPROBE_PATH should only be set if you're providing FFMPEG/FFPROBE binaries yourself via a mounted volume. Setting this blocks the normal downloading process under the assumption that you're providing them somewhere
- SMA_FFMPEG_URL needs to be a URL not a path, this is to replace the default default https://johnvansickle.com source of FFMPEG. This does nothing when the above  SMA_FFMPEG/FFPROBE_PATH are set
- SMA_STRIP_COMPONENTS only needs to be modified if you're providing a different download URL that is packaged differently. This does nothing if  SMA_FFMPEG/FFPROBE_PATH is set and won't help if SMA_FFMPEG_URL isn't a URL. The code this impacts is just one line shown below
```
    wget -q ${SMA_FFMPEG_URL} -O /tmp/ffmpeg.tar.xz
    tar --exclude='*.html' --exclude='*.txt' -xJf /tmp/ffmpeg.tar.xz -C /usr/local/bin --strip-components ${SMA_STRIP_COMPONENTS}
```
- You probably don't need to be passing all these drivers and environment variables for intel transcoding
- Not sure why you're modifying the S6 environment variables either but I'll leave that alone

The biggest issue here is that you're essentially telling the script you are going to provide FFMPEG and then not doing so, and you're also blocking the FFMPEG_URL with an invalid URL

I made  the following test
```yml
  sonarrtest:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarrtest
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=mdhiggins/sma-mod:latest
      - SMA_USE_REPO=true
      - SMA_UPDATE=true
      - SMA_HWACCEL=true
```

And I am able to open
```
michael@plexrack:~$ dcp exec sonarrtest bash
root@abe0899e3fac:/# ffmpeg -hwaccels
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hardware acceleration methods:
vdpau
cuda
vaapi
qsv
drm
opencl

root@abe0899e3fac:/# /usr/local/sma/venv/bin/python3 /usr/local/sma/manual.py
Manual processor started.
Python 64-bit 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0].
Guessit version: 3.7.1.
/usr/local/sma/venv/bin/python3
Loading config file /usr/local/sma/config/autoProcess.ini.
Enter path to file:
#:

root@abe0899e3fac:/# cd /dev/dri
root@abe0899e3fac:/dev/dri# ls -la
total 0
drwxr-xr-x 2 root root            80 Apr 11 10:58 .
drwxr-xr-x 6 root root           360 Apr 11 10:58 ..
crw-rw---- 1 root video     226,   0 Apr 11 10:58 card0
crw-rw---- 1 root videoj3e5 226, 128 Apr 11 10:58 renderD128
```

The repo included FFMPEG already has VAAPI and QSV included so this is a very easy way to get that via SMA_USE_REPO

I would then stop modifying autoProcess.ini and let the script auto configure the FFMPEG path

SMA_MOD also includes a script that sets the /dev/dri permissions so you don't need to do anything there except make sure you have appropriate permissions on your host machine

Obviously you'll need to include the mount points for your data/configuration files which I assume are omitted here for brevity

**Comment by mdhiggins** [comment]
You aren't supposed to mount FFMPEG, that was the whole point of using the repo and not needing to include all the extra stuff I outlined above

The only volumes you need are your media and config folders. Something like this. Let the container handle FFMPEG

```
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/downloads:/downloads
```

**Comment by mdhiggins** [comment]
What do your permissions look like on the host container for /dev/dri?

**Comment by mdhiggins** [comment]
Does your user (1000) belong to the video/render groups?

**Comment by mdhiggins** [comment]
You're using your same docker user as your main user? Cause that would impact things and being able to use it outside the container does not mean the permissions carry over necessarily

Also if you could share the whole FFMPEG command I can take a look

**Comment by mdhiggins** [comment]
Hm, can you check and see if `intel-media-driver` and `libva` packages are installed?

**Comment by mdhiggins** [comment]
If you take the original command

```
/usr/bin/ffmpeg -fix_sub_duration -hwaccel vaapi -hwaccel_output_format vaapi -i "/storage/tv/file.mkv.original" -vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset fast -profile:v main10 -level 5.2 -tag:v hvc1 -qp 0 -vaapi_device /dev/dri/renderD128 -vf "format=p010|vaapi,hwupload,scale_vaapi=format=p010" -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 copy -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y "/storage/tv/file.mkv"
```

And remove the filter part and run it manually
```
/usr/bin/ffmpeg -fix_sub_duration -hwaccel vaapi -hwaccel_output_format vaapi -i "/storage/tv/file.mkv.original" -vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset fast -profile:v main10 -level 5.2 -tag:v hvc1 -qp 0 -vaapi_device /dev/dri/renderD128 -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 copy -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y "/storage/tv/file.mkv"
```

Does that change anything?

**Comment by mdhiggins** [comment]
Actually I'm surprised you were able to install that before, I assume sonarr is on alpine these days and I don't think that has the nonfree package

**Comment by mdhiggins** [comment]
Ah nevermind I'm on the develop branch which has switched over to alpine, guess the latest is still ubuntu for now

**Comment by mdhiggins** [comment]
I'm guessing this is some kind of dependency missing and all searching over the error usually points to be people recommending installing the non-free variant. Not sure what else could be missing

**Comment by mdhiggins** [comment]
```
            libva-drm2 \
            libva2 \
            i965-va-driver \
            intel-media-va-driver \
            intel-media-va-driver-non-free \
            mesa-va-drivers
```

Those are the packages that are installed on ubuntu based systems using the SMA_HWACCEL option, might want to check and see if they actually being installed and add any missing ones

**Comment by mdhiggins** [comment]
Whoops fixed, that was supposed to be in the alpine package list
